---
- name: Construct Zabbix Release RPM URL based on RHEL version
  ansible.builtin.set_fact:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/8.0/release/rhel/{{ ansible_distribution_major_version }}/noarch/\
      zabbix-release-latest-8.0.el{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Import the Zabbix GPG key
  ansible.builtin.rpm_key:
    key: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install the Zabbix 8.0 release repository
  ansible.builtin.dnf:
    name: "{{ zabbix_repo_url }}"
    state: present
